### ISSUE TITLE
Release v19.4 checklist

### ISSUE THREAD

**Issue by jasonlharvey** [nasa/gunns#74]
Software release checklist for minor release v19.4:

- [x] Review code changes
- [x] Update GunnsDraw version label & re-export all drawings
- [x] make sure all new source folders are in the lib makefiles
- [x] check linux (gcc) and OSX (clang) compilations, clean up all compile warnings
- [x] Final check all UT’s and test sims
- [x] Document new features
- [x] Add new GunnsDraw shape help pages
- [x] Update release notes
- [x] Tag final commit
- [x] Close issues & tag with release milestone
- [x] Email release news to the mailing list
- [x] Notify NASA Software Release Coordinator of new release
